spring.application.name=restaurant-finder-app
spring.data.mongodb.uri=mongodb+srv://root:root@restaurantcluster.i8vpb.mongodb.net/?retryWrites=true&w=majority&appName=restaurantCluster
spring.data.mongodb.database=restaurant